### PR TITLE
Try to implement the grammar in fluent.mjs in tree-sitter

### PR DESCRIPTION
**Pull request by Pike**
We wonder if there's a difference in the capabilities of the parser logic in fluent.mjs and parsers.mjs to tree-sitter, or if the parser compiler in tree-sitter is just over protective.

The current state fails on tree-sitter generate with:

Error: Unresolved conflict for symbol sequence:

    '  …neBreak_repeat1  •  '

    Possible interpretations:

    '  …  (lineBreak  lineBreak_repeat1)  •  '
      2:  (lineBreak_repeat1  lineBreak_repeat1  •  lineBreak_repeat1)

    Possible resolutions:

      1:  Specify a left or right associativity in `lineBreak`
      2:  Add a conflict for these rules: `lineBreak`

### CODE REVIEW

**Comment by Pike** [comment]
@maxbrunsfeld, could you help us out here? This is related to my attempt to build a tree-sitter grammar for https://projectfluent.org/, and we're hitting these error messages a lot.

Stas and I went in and adapted a different parser generator w/out lookahead, and this one doesn't expose the same challenges, and we're not sure if it's a bug on our side or the tree-sitter compiler.

`fluent.mjs` and `grammar.js` are the two grammars, you can run the mjs one via `npm start`, the tree-sitter one fails on `tree-sitter generate`.

We tried to sprinkle `prec()` in various places, but to no avail, too.

**Comment by maxbrunsfeld** [comment]
Yeah, that error message is indicating that there is an ambiguity in your tree-sitter grammar. The `body` rule can contain multiple repeated `lineBreak` nodes, but the `lineBreak` rule itself can contain multiple repeated `\n` characters. So for example, if you see ten `\n` characters, how should they be grouped into `lineBreak`s? There are many possible parses.

I'd suggest maybe removing one repeat or the other?

**Comment by Pike** [comment]
Thanks for taking a look, Max.

That was a simple fix that just got me a small step forward.

I've added two commits, one for the line break, which brings us to

    Error: Unresolved conflict for symbol sequence:

      'key'  '='  ' '  •  ' '  …

    Possible interpretations:

      1:  'key'  '='  (inlineChar  ' ')  •  ' '  …
      2:  'key'  '='  (inlineSpace_repeat1  ' ')  •  ' '  …

    Possible resolutions:

      1:  Add a conflict for these rules: `inlineChar`

That's the optional whitespace around "=", which overlaps with " " in the text production. If I remove the trailing whitespace (second commit), I get further to

    Error: Unresolved conflict for symbol sequence:

    '  …ey'  '='  pattern  •  '

    Possible interpretations:

    '  …  (message  'key'  '='  pattern)  •  '
      2:  (message  'key'  '='  pattern  •  message_repeat1)

    Possible resolutions:

      1:  Specify a left or right associativity in `message`
      2:  Add a conflict for these rules: `message`

And then stas went in and landed a couple of prec() changes, and now the grammar does get generated.

But it doesn't parse the test example that we thought we'd write a grammar for ;-)

      ♢ The fluent language 
     
      basic
        ✗ Simple 
            »        
            actual expected 
         
            (body (entry (message (pattern))) (ERROR) (ERROR)attribute (ERROR) (ERROR) (ERROR))pattern))))) 
             // macros.js:14

So right now, we're a bit stuck.

We've also looked at our whiteboard and think we're doing a LL(k) grammar, which might be hard to express in LR(1)?

**Comment by maxbrunsfeld** [comment]
> And then stas went in and landed a couple of prec() changes, and now the grammar does get generated.

Yeah, I don't think precedence is the right solution here.

All of these ambiguities are arising because of the way the grammar is broken down into tokens. Like you said, Tree-sitter wants you to write an LR(1) grammar. The '1' in LR(1) refers to there being only one *token* of lookahead. So it's really important that you break things into 'tokens' in a way that makes sense.

By default, each string or RegExp literal in the grammar is a separate token. You can also use the `token` function to group arbitrarily complex rules into atomic tokens. But the way that your grammar is currently written, every space, tab, carriage return, and line feed character is considered a separate token. In other words, if there are two spaces in a row, the parser must process each one separately, and upon seeing the second space, it needs to decide how to interpret the first one. This is very limiting.

You may want to wrap rules like `inlineSpace` in `token`, or just express them as regexes. Whichever is easier.

> We've also looked at our whiteboard and think we're doing a LL(k) grammar, which might be hard to express in LR(1)?

From the docs, the language *looks* pretty simple (though I could be missing a lot). I think LR(1) should be fine, but if there do end up being true ambiguities in the language, you can whitelist those ambiguities to be resolved at runtime using the `conflicts` field on the grammar. This has some performance cost, but it's similar to the inefficiencies that you get with LL(k)'s backtracking.

**Comment by maxbrunsfeld** [comment]
Also, I don't get why you need to deal with whitespace so explicitly. I know that newlines are significant, but that shouldn't be a problem; you can still include whitespace in your `extras` field (as is the default), and the newlines will automatically be treated as separate tokens only in cases where a newline token is valid. This is what we do with the [`terminator` rule in the Go grammar](https://github.com/tree-sitter/tree-sitter-go/blob/059f55a4fcc90344eab9f92ac314df59760ccb6b/grammar.js#L49), and in the [bash grammar](https://github.com/tree-sitter/tree-sitter-bash/blob/73d6705bc28b07a675da8f96c4620ba76a668894/grammar.js#L438) for example.

Maybe I'm missing something though; can you explain a bit more why you can't have whitespace be handled via `extras`, and need all this stuff like `inlineSpace`?

**Comment by Pike** [comment]
Let's start with an example:

    one = first line
        second = line
    second = line
    third = line

parses as

- `one` : `first line\nsecond = line`
- `second` : `line`
- `third`: `line`

To detect that `  second = line` is actually part of the value for `one`, we need to explicitly white space.

In my experiments, I couldn't see in the parser if "`  `" was in the stream or not, so I couldn't tell the difference between line 2 and 3.

Re the tokens, I did try to put `breakIndent` into a token, but that didn't break into new grounds at the point I was at.

We also ended up refactoring the grammar, but that's not in the ebnf yet. We folded \n and eof into a single token, which makes the grammar in https://github.com/stasm/fluent-kombi/blob/1ec757f7b220b29b1727556c4bc49a1bad7435db/grammar.mjs a lot more straight forward. Due to js being js, that grammar needs to be read bottom-up.

About `conflicts`, what's in those? I looked at where they're used, and couldn't figure out what the meaning of that is.

**Comment by maxbrunsfeld** [comment]
Thanks for the great explanation.

I hacked together what could be the start of a Tree-sitter grammar for Fluent: https://github.com/tree-sitter/tree-sitter-fluent. There's probably a lot missing and I probably have some misunderstandings of how the language works, but it might be a good starting point anyway.

To address your point about the newlines, I had to use an external scanner (a small amount of hand-written C code that can execute [arbitrary logic](https://github.com/tree-sitter/tree-sitter-fluent/blob/722d332ed52b71ecb41a258763803acdd38c1f20/src/scanner.c#L19-L32) in order to decide what token to produce). In the external scanner, I only produce a `terminator` token if there's an EOF or a newline not followed by whitespace. It may actually be possible to do this without even using an external scanner, but this seemed like a fairly straightforward way to do it.

**Pull request closed without merging**
